const weatherType = {
  // 吹雪或飘雪
  'type_1': 'snowing',
  // 细雨
  'type_2': 'light-rain',
  // 重的细雨
  'type_3': 'rain',
  // 毛毛细雨
  'type_4': 'light-rain',
  // 重的细雨/雨
  'type_5': 'rain',
  // 浅色毛毛雨/雨
  'type_6': 'light-rain',
  // 尘暴
  'type_7': 'floating-dust',
  // 多雾路段
  'type_8': 'minFog',
  // 冻雨
  'type_9': 'freezing-rain',
  // 大冻雨/冻雨
  'type_10': 'freezing-rain',
  // 微弱的冻雨/冻雨
  'type_11': 'freezing-drizzle',
  // 冷冻雾
  'type_12': 'minFog',
  // 沉重的冻雨
  'type_13': 'heavy-freezing-rain',
  // 微弱的冻雨
  'type_14': 'freezing-drizzle',
  // 漏斗云/龙卷风
  'type_15': 'tornado',
  // 冰雹淋浴(阵冰雹)
  'type_16': 'hailstone',
  // 冰
  'type_17': 'hailstone',
  // 闪电
  'type_18': 'lightning',
  // 薄雾
  'type_19': 'fog',
  // 该地区降水
  'type_20': 'rain',
  // 雨
  'type_21': 'rain',
  // 大雨和雪
  'type_22': 'rain-snow',
  // 小雨和雪
  'type_23': 'rain-snow',
  // 阵雨
  'type_24': 'shower',
  // 雨, 部分多云
  'type_21, type_42': 'shower',
  // 倾盆大雨
  'type_25': 'rain',
  // 小雨
  'type_26': 'light-rain',
  // 雨, 阴云密布
  'type_21, type_41': 'light-rain',
  // 天空覆盖率下降(晴转阴)
  'type_27': 'partly-cloudy-day',
  // 天空覆盖范围增加(阴转晴)
  'type_28': 'partly-cloudy-day',
  // 天空不变
  'type_29': 'partly-cloudy-day',
  // 烟雾或阴霾
  'type_30': 'fog',
  // 雪
  'type_31': 'snow',
  // 雪雨
  'type_32': 'rain-snow',
  // 阵雪
  'type_33': 'snow-shower',
  // 暴雪
  'type_34': 'snow',
  // 小雪
  'type_35': 'light-snow',
  // 暴风雪
  'type_36': 'snowstorm',
  // 雷雨
  'type_37': 'thunderstorm',
  // 打雷
  'type_38': 'thunder',
  // 钻石尘埃(沙尘暴)
  'type_39': 'sandStorm',
  // 冰雹
  'type_40': 'hailstone',
  // 阴云密布
  'type_41': 'cloudy',
  // 部分多云
  'type_42': 'partly-cloudy-day',
  // 晴朗
  'type_43': 'clear-day'
}

export default weatherType;